# -*- coding: utf-8 -*-
"""Prak Algo(6)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvkh3MwqlmALeVBatMSIjm3oUbDfCiKf
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
import math
print("GENAP -> Perpindahan (diketahui v0 konstan)")
v0=int(input("masukkan v0= "))
a=int(input("masukkan a= "))
s=int(input("masukkan s= "))

r=v0**2+2*a*s
akar=math.sqrt(r)
print(f"Jarak tempuh jika kecepatan awal adalah= {v0} dengan percepatan {a} dan jarak tempuh= {s}, adalah {akar}")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @       @    @@@@@@@    @@@@@@@   @        @ ')

def main():
    while True:
        print("===KALKULATOR MENCARI LUAS===")
        print("1.) Kubus")
        print("2.) Balok")
        print("3.) Tabung")
        print("4.) Kerucut")
        print("5.) Bola")
        print("6.) Keluar")

        opsi = input(">>> ")
        if opsi.isdigit():
            if opsi == "1":
                kubus()
                return exit
            elif opsi == "2":
                balok()
                return exit
            elif opsi == "3":
                tabung()
                return exit
            elif opsi == "4":
                kerucut()
                return exit
            elif opsi == "5":
                bola()
                return exit
            elif opsi == "6":
                return exit
            else:
                continue
        elif opsi == "exit":
            return exit
        else:
            continue

def kubus():
    while True:
        print("===Menghitung Luas Kubus===")
        panjangSisi = input("Masukan panjang sisi >> ")
        if panjangSisi.isdigit():
            panjangSisi = int(panjangSisi)
            luasKubus = 6 * panjangSisi**2
            print(f"Luas Kubus adalah : {luasKubus}")
            opsi = input("lanjut menghitung?? (y/n) >> ").lower()
            if opsi == "y":
                continue
            else:
                return main()
        elif panjangSisi == "exit":
            return main()
        else:
            print("Masukan angka yang benar!")
            continue

def balok():
    while True:
        print("===Menghitung Luas Balok===")
        panjang = input("Masukan Sisi Panjang >> ")
        if panjang.lower() == "exit":
            return main()
        lebar = input("Masukan Sisi Lebar >> ")
        tinggi = input("Masukan Sisi Tinggi >> ")
        if (panjang and lebar and tinggi).isdigit():
            panjang, lebar, tinggi = (int(panjang), int(lebar), int(tinggi))
            if lebar < panjang:
                luasBalok = ((2*panjang*lebar) + (2*lebar*tinggi) + (2*panjang*tinggi))
                print(f"Luas Balok adalah : {luasBalok}")
                opsi = input("Lanjut Menghitung? (y/n) : ").lower()
                if opsi == "y":
                    continue
                else:
                    return main()
            else:
                print("Sisi Panjang harus lebih besar dari Sisi Lebar!")
                continue
        else:
            print("Masukan angka yang benar!")
            continue

def tabung():
    while True:
        print("===Menghitung Luas Tabung===")
        jariJari = input("Masukan Jari-Jari >> ")
        if jariJari == "exit":
            return main()
        tinggi = input("Masukan Tinggi Tabung >> ")
        if (jariJari and tinggi).isdigit():
            jariJari, tinggi = int(jariJari), int(tinggi)
            luasTabung = (math.pi * jariJari**2) + ((2*math.pi*jariJari) * tinggi)
            print(f"Luas Tabung adalah : {luasTabung}")
            opsi = input("Lanjut Menghitung? (y/n) : ").lower()
            if opsi == "y":
                continue
            else:
                return main()
        else:
            print("Masukan angka yang benar!")
            continue
import math
def kerucut():
    while True:
        print("===Menghitung Luas Kerucut===")
        jariJari = input("Masukan Jari Jari >> ")
        if jariJari == "exit":
            return main()
        s = input("Masukan Garis Pelukis >> ")
        if (jariJari and s).isdigit():
            jariJari, s = int(jariJari), int(s)
            luasKerucut = (math.pi*jariJari*s) + (math.pi*jariJari*2)
            print(f"Luas Kerucut Adalah : {luasKerucut}")
            opsi = input("Lanjut Menghitung? (y/n) : ").lower()
            if opsi == "y":
                continue
            else:
                return main()
        else:
            print("Masukan angka yang benar!")
            continue

def bola():
    while True:
        print("===Menghitung Luas Bola===")
        jariJari = input("Masukan Jari Jari >> ")
        if jariJari == "exit":
            return main()
        if jariJari.isdigit():
            jariJari = int(jariJari)
            luasBola = 4*math.pi*jariJari**2
            print(f"Luas Bola adalah : {luasBola}")
            opsi = input("Lanjut Menghitung? (y/n) : ").lower()
            if opsi == "y":
                continue
            else:
                return main()
        else:
            print("Masukan angka yang benar!")
            continue

if __name__ == "__main__":
    main()